#define L1D_RMPAGE_BLOCKS_BITS (LOG2_PAGE_SIZE - LOG2_BLOCK_SIZE)
#define L1D_RMPAGE_BLOCKS (1 << L1D_RMPAGE_BLOCKS_BITS)
#define L1D_RMPAGE_OFFSET_MASK (L1D_RMPAGE_BLOCKS - 1)
#define L1D_RMMAX_NUM_BURST_PREFETCHES 3
#define L1D_RMBERTI_RM_CTR_MED_HIGH_CONFIDENCE 2

// TIME AND OVERFLOWS
#define L1D_RMTIME_BITS 16
#define L1D_RMTIME_OVERFLOW ((uint64_t)1 << L1D_RMTIME_BITS)
#define L1D_RMTIME_MASK (L1D_RMTIME_OVERFLOW - 1)

// CURRENT PAGES TABLE
#define L1D_RMCURRENT_PAGES_TABLE_INDEX_BITS 6
#define L1D_RMCURRENT_PAGES_TABLE_ENTRIES ((1 << L1D_RMCURRENT_PAGES_TABLE_INDEX_BITS) - 1) // Null pointer for prev_request
#define L1D_RMCURRENT_PAGES_TABLE_NUM_BERTI_RM 10
#define L1D_RMCURRENT_PAGES_TABLE_NUM_BERTI_RM_PER_ACCESS 7

// PREVIOUS REQUESTS TABLE
#define L1D_RMPREV_REQUESTS_TABLE_INDEX_BITS 10
#define L1D_RMPREV_REQUESTS_TABLE_ENTRIES (1 << L1D_RMPREV_REQUESTS_TABLE_INDEX_BITS)
#define L1D_RMPREV_REQUESTS_TABLE_MASK (L1D_RMPREV_REQUESTS_TABLE_ENTRIES - 1)
#define L1D_RMPREV_REQUESTS_TABLE_NULL_POINTER L1D_RMCURRENT_PAGES_TABLE_ENTRIES

// PREVIOUS PREFETCHES TABLE
#define L1D_RMPREV_PREFETCHES_TABLE_INDEX_BITS 9
#define L1D_RMPREV_PREFETCHES_TABLE_ENTRIES (1 << L1D_RMPREV_PREFETCHES_TABLE_INDEX_BITS)
#define L1D_RMPREV_PREFETCHES_TABLE_MASK (L1D_RMPREV_PREFETCHES_TABLE_ENTRIES - 1)
#define L1D_RMPREV_PREFETCHES_TABLE_NULL_POINTER L1D_RMCURRENT_PAGES_TABLE_ENTRIES

// RECORD PAGES TABLE
// #define L1D_RMRECORD_PAGES_TABLE_INDEX_BITS 10
#define L1D_RMRECORD_PAGES_TABLE_ENTRIES (((1 << 10) + (1 << 8) + (1 << 7)) - 1) // ((1 << L1D_RMRECORD_PAGES_TABLE_INDEX_BITS) - 1) // Null pointer for ip table
#define L1D_RMTRUNCATED_PAGE_ADDR_BITS 32                                        // 4 bytes
#define L1D_RMTRUNCATED_PAGE_ADDR_MASK (((uint64_t)1 << L1D_RMTRUNCATED_PAGE_ADDR_BITS) - 1)

// IP TABLE
#define L1D_RMIP_TABLE_INDEX_BITS 10
#define L1D_RMIP_TABLE_ENTRIES (1 << L1D_RMIP_TABLE_INDEX_BITS)
#define L1D_RMIP_TABLE_INDEX_MASK (L1D_RMIP_TABLE_ENTRIES - 1)
#define L1D_RMIP_TABLE_NULL_POINTER L1D_RMRECORD_PAGES_TABLE_ENTRIES

# define BERTI_RM_REGION_HISTORY_SETS    64
# define BERTI_RM_REGION_HISTORY_WAYS    12